# Python для анализа данных

*Алла Тамбовцева, Татьяна Рогович, НИУ ВШЭ*

## Массивы `NumPy`

### Базовые операции с массивами

Сегодня мы познакомимся с библиотекой `NumPy` (сокращение от *Numeric Python*), которая часто используется в задачах, связанных с машинным обучением.

Чтобы мы смогли на конкретных примерах увидеть, зачем эта библиотека используется, давайте её импортируем. Если вы уже устанавливали Anaconda, то библиотека `numpy` также была установлена на ваш компьютер. Проверим: импортируем библиотеку с сокращённым названием, так часто делают, чтобы не «таскать» за собой в коде длинное название. Сокращение `np` для библиотеки `numpy` – распространённое, можно даже сказать, общепринятое, его часто можно увидеть в документации или официальных тьюториалах.

In [1]:
import numpy as np

Возможности:
   - поддержка многомерных массивов (включая матрицы);
   - поддержка высокоуровневых математических функций, предназначенных для работы с многомерными массивами.  
    
Так же numpy лежить в основе датафреймов pandas, и многие вещи (фильтрация, индексирование, математические операции), которые обсудим в этом уроке, потом транслируются в pandas.

В `Python` к числовым типам относятся:
   - int
   - float
   - bool
   - complex   
   
В `numpy` имеются эти типы, а также обёртки над этими типами, которые **используют реализацию типов на C**, например, `int8`, `int16`, `int32`, `int64` (подробнее о типах данных `numpy` можно прочитать [здесь](https://www.numpy.org/devdocs/user/basics.types.html)). За счёт того, что используются типы данных из C, numpy получает ускорение операций.

In [3]:
type(32), type(np.int32(32)), type(np.int64(32))

(int, numpy.int32, numpy.int64)

**Переполнение**

В связи с особенностями типов `numpy` важно помнить о переполнении.   
Например, 64-битный int в С хранит числа от -9223372036854775808 до 9223372036854775807

In [6]:
2**64

18446744073709551616

In [7]:
print(np.int64(1e10)) # все поместилось

10000000000

In [8]:
print(np.int64(10e18)) # не поместилось

OverflowError: Python int too large to convert to C long

In [4]:
print(10e18) # а в стандартный питоновский integer - помещается

1e+19

# Массивы Ndarray

Основыным объектом `numpy` является Ndarray – это n-мерный массив (сокращение от *n-dimensional array*), структура данных, которая позволяет хранить набор элементов одного типа: либо только целые числа, либо числа с плавающей точкой, либо строки, либо булевы (логические) значения. 

Производить вычисления с массивами гораздо быстрее и эффективнее чем со списками.

Массивы могут быть одномерными, то есть визуально ничем не отличаться от простого списка значений.

In [9]:
import numpy as np

np.array([0, 2, 3, 4 ])

array([0, 2, 3, 4])

А могут быть многомерными (n-мерными), то есть представлять собой вложенный список («список списков»):

In [11]:
np.array([[1, 2], 
          [1, 0,]])  # двумерный

array([[1, 2],
       [1, 0]])

Или даже «список таблиц»:

In [7]:
x = np.array([[[6, 3],
        [6, 8]],
      [[1, 100],
        [0, 1]]])  # трехмерный

2.5

In [13]:
x[1][0][1]# вторая колонка первой строки второго измерения

100

Мы чаще всего будем работать с двумерными массивами. Про двумерный массив можно думать как про матрицу или про таблицу. Так, массив во втором примере выше можно рассматривать как таблицу, состояшую из двух строк и трёх столбцов, как таблицу $2 \times 3$ (сначала указывается число строк, затем – число столбцов). Отсюда следует важный факт: число элементов в списках внутри массива должно совпадать. Проверим на примере – возьмём списки разной длины, то есть списки, состоящие из разного числа элементов, и объединим их в массив:

In [18]:
lst = [[0, 0, 1],
         [0, 1]]
lst

[[0, 0, 1], [0, 1]]

In [19]:
np.array([[0, 0, 1],
         [0, 1]])

<ipython-input-19-372b51043c53>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  np.array([[0, 0, 1],

array([list([0, 0, 1]), list([0, 1])], dtype=object)

Получилось что-то немного странное. Никакой ошибки Python не выдал, но воспринимать этот объект как полноценный массив он уже не будет: он будет считать, что в такой таблице у нас есть две строки и ноль столбцов!

Теперь давайте посмотрим, что будет, если мы попробуем объединить в массив объекты разных типов, например, целые числа и числа с плавающей точкой:

In [13]:
np.array([[5, 8.2], 
         [1.2, 1,]])

array([[5. , 8.2],
       [1.2, 1. ]])

In [14]:
np.array([[5, 8.2], 
         [1.2, 'ba']])

array([['5', '8.2'],
       ['1.2', 'ba']], dtype='<U32')

Все элементы были автоматически приведены к одному типу (можно считать, что тип *float* «сильнее» типа *integer*). Можете самостоятельно проверить, что будет, если мы «смешаем» в списке строковые и числовые значения.

Чем же удобны массивы? Во-первых, они занимают меньше места и памяти. Во-вторых, с ними очень удобно работать: все операции над массивами будут производиться поэлементно: то есть, для выполнения действий над каждым элементом массива, нам не придется использовать какие-то специальные конструкции вроде циклов, мы сможем обращаться сразу ко всему массиву. Например, давайте представим, что у нас есть массив со значениями явки на выборы в долях, а мы хотим получить результаты в процентах (домноженные на 100).

В отличие от питоновских листов - ndarray - это полноценный вектор. И он поддерживает операции над векторами. Так пример выше - это умножение вектора на скаляр.

In [15]:
s = [2,1]
s*2

[2, 1, 2, 1]

In [18]:
turnout = np.array([0.62, 0.43, 0.79, 0.56])
turnout

array([0.62, 0.43, 0.79, 0.56])

In [19]:
2*turnout

array([1.24, 0.86, 1.58, 1.12])

In [20]:
v1 = np.array([2,1])

In [21]:
v1*2

array([4, 2])

Чтобы домножить каждое число в массиве на 100, нам достаточно домножить на 100 `turnout`:

In [23]:
def power(x, p = 2):
    return x**p

In [24]:
0.62**2

0.3844

In [25]:
power(turnout, 2)

array([0.3844, 0.1849, 0.6241, 0.3136])

In [26]:
turnout * 100  # готово!

array([62., 43., 79., 56.])

Точно так же можем производить операции с несколькими массивами — действия будут выполняться поэлементно (сложение векторов)

In [27]:
[2, 3, 5]+[0, 8, 6]

[2, 3, 5, 0, 8, 6]

In [3]:
# поэлементное сложение векторов
A = np.array([[2, 3, 5], [2, 3, 5]])
B = np.array([[0, 8, 6], [0, 8, 6]])

A - B

array([[ 2, -5, -1],
       [ 2, -5, -1]])

In [29]:
np.array([1,1]) + np.array([1,2])

array([2, 3])

In [4]:
# полеэментное умножение векторов
A * B

array([[ 0, 24, 30],
       [ 0, 24, 30]])

Выполним сразу несколько действий — посчитаем явку на основе массивов с числом действительных и недействительных бюллетеней.

In [5]:
valid = np.array([32, 45, 50, 44])# действительные бюллетени
invalid = np.array([3, 11, 2, 6]) # недействительные бюллетени
total = np.array([65, 72, 80, 100]) # всего зарегистрированных избирателей

(valid + invalid) / total * 100

array([53.84615385, 77.77777778, 65.        , 50.        ])

In [10]:
import numpy as np

a = np.array([1,2,3,4,5,6,7])
b = np.array([2,3,6,4,3,1,20])

In [14]:
abs(b-a).mean()/a.mean()

0.8928571428571429

In [15]:
abs(b-a).mean()

3.5714285714285716

In [17]:
np.sqrt(((b-a)**2).sum())

14.45683229480096

# <a id="Массивы ndarray и операции с ними"><span style="color:green">Массивы ndarray и операции с ними</span></a>

Наиболее важные атрибуты объектов ndarray:
1. **`ndarray.ndim`** - число измерений (чаще их называют "оси") массива.
  
2. **`ndarray.shape`** - размеры массива, его форма. Это кортеж натуральных чисел, показывающий длину массива по каждой оси. Для матрицы из n строк и m столбов, shape будет (n,m). Число элементов кортежа shape равно ndim.
3. **`ndarray.size`** - количество элементов массива. Очевидно, равно произведению всех элементов атрибута shape.
4. **`ndarray.dtype`** - объект, описывающий тип элементов массива. Можно определить dtype, используя стандартные типы данных Python. Можно хранить и numpy типы, например: bool, int16, int32, int64, float16, float32, float64, complex64

Одномерный массив

In [31]:
M = np.array([[2, 5], 
              [6, 8], 
              [1, 3]])
M

array([[2, 5],
       [6, 8],
       [1, 3]])

In [32]:
M.dtype

dtype('int64')

Массивы бывают многомерными, значит, у массива есть число измерений. Давайте его найдём:

In [33]:
M.ndim  # dimensions

2

Действительно, всего два измерения: чтобы указать на число 5 из этого массива, нам понадобятся всего две координаты – номер строки и номер столбца. Теперь посмотрим на форму или вид массива (*shape*):

In [34]:
M.shape  # 3 строки и 2 столбца, т.е. 3 списка по 2 элемента

(3, 2)

Кроме того, можем найти общее число элементов в массиве, его длину, размер (*size*):

In [35]:
M.size  # всего 6 элементов

6

### Работа с элементами массива

Если нам нужно обратиться к элементам массива, то эта операция будет похожа на работу со вложенными списками:

In [36]:
M.astype(np.int32)

array([[2, 5],
       [6, 8],
       [1, 3]], dtype=int32)

In [37]:
M[0]  # весь первый список в M

array([2, 5])

In [38]:
M[0][1]  # второй элемент первого списка в M

5

Или не совсем как со списками, без двойных скобок:

In [39]:
M[0, 1]

5

Ещё можно выбирать сразу несколько элементов массива. Для этого воспользуемся срезами (*slices*):

In [41]:
M[0:2]  # с элемента с индексом 0 до элемента с индексом 1 включительно

array([[2, 5],
       [6, 8]])

Обратите внимание: правый конец среза не включается.

Концы среза можно опускать, если нас интересуют все элементы, начиная с некоторого элемента и до конца массива или начиная с первого элемента массива и до некоторого элемента (правый конец точно так же включаться не будет):

In [40]:
M

array([[2, 5],
       [6, 8],
       [1, 3]])

In [42]:
M[1:, ] # с элемента с индексом 1 до конца

array([[6, 8],
       [1, 3]])

In [43]:
M[:2] # с начала массива до элемента с индексом 1 включительно

array([[2, 5],
       [6, 8]])

Еще можно взять полный срез – выбрать все элементы массива:

In [44]:
print(M[:])

[[2 5]
 [6 8]
 [1 3]]

Кроме того, при выборе элементов можно выставлять шаг. По умолчанию мы выбираем все элементы подряд, шаг равен 1, но это можно изменить:

In [50]:
M[0:3:2]  # с нулевого по третий через 2

array([[2, 5],
       [1, 3]])

Концы среза по-прежнему можно опускать:

In [38]:
M[0::2]

array([[2, 5],
       [1, 3]])

Или сделать более интересную вещь, взять отрицательный шаг и выбрать все элементы в обратном порядке, с конца:

In [39]:
M[::-1]

array([[1, 3],
       [6, 8],
       [2, 5]])

### Ещё про операции с массивами

Теперь посмотрим на другие операции с массивами. Создадим простой одномерный массив, содержащий оценки группы школьников:

In [45]:
marks = np.array([5, 4, 3, 5, 5, 4, 3, 4]) 
marks

array([5, 4, 3, 5, 5, 4, 3, 4])

Найдем самую плохую, минимальную оценку:

In [46]:
marks.min()

3

А теперь самую высокую, максимальную:

In [47]:
marks.max()

5

И средний балл:

In [48]:
marks.mean()

4.125

Медиану мы так не найдём — нет метода `median()`, но зато есть такая функция:

In [49]:
np.median(marks)

4.0

In [60]:
marks.so

array([5, 4, 3, 5, 5, 4, 3, 4])

In [52]:
MY_ARRAY = np.array([[1,2,3,4,5], [2,3,4,5,7]])

MY_ARRAY = MY_ARRAY.flatten()
# MY_ARRAY.sort()

In [53]:
MY_ARRAY

array([1, 2, 3, 4, 5, 2, 3, 4, 5, 7])

In [47]:
np.median(M)

4.0

А теперь найдем номер ученика с самой высокой оценкой:

In [67]:
marks.argmax()

0

In [55]:
marks.cumsum()

array([ 5,  9, 12, 17, 22, 26, 29, 33])

И номер ученика с самой низкой оценкой:

In [54]:
marks.argmin()

2

**Внимание:** если таких несколько, будет выведено первое совпадение, как для `argmin()`, так и для`argmax()`.

Конечно, мы не сможем сейчас рассмотреть все доступные методы, относящиеся к массивам (некоторые часто используемые методы мы еще будем обсуждать в следующем модуле), но при желании на перечень доступных методов можно посмотреть, набрав название массива, поставив точку и нажав на *Tab* (показать).

Теперь посмотрим на многомерный массив, для удобства возьмём двумерный:

In [56]:
grades = np.array([[3, 5, 5, 4, 3], 
                   [3, 3, 4, 3, 3], 
                   [5, 5, 5, 4, 5]])

In [57]:
grades.T

array([[3, 3, 5],
       [5, 3, 5],
       [5, 4, 5],
       [4, 3, 4],
       [3, 3, 5]])

Пусть это будут оценки трёх студентов 5 контрольных работ. Попробуем теперь найти средний балл за контрольные по каждому группе. Для этого необходимо указать, по какому измерению мы будем двигаться (грубо говоря, по строкам или столбцам):

In [59]:
grades.mean(axis = 1) # по строкам, три оценки - одна для каждого студента

array([4. , 3.2, 4.8])

А теперь найдем средний балл по каждой контрольной работе:

In [76]:
grades.mean(axis = 0) # по столбцам, пять оценки - одна для каждой работы

array([3.66666667, 4.33333333, 4.66666667, 3.66666667, 3.66666667])

In [92]:
x = (np.random.rand(10)*10)
x
# .astype(np.int32)

array([6.68464997, 0.65698545, 2.79699014, 4.82929004, 9.7652358 ,
       8.90254416, 3.47854617, 9.50260785, 1.03957477, 7.55318421])

In [94]:
x - x.astype(np.int32)

array([0.68464997, 0.65698545, 0.79699014, 0.82929004, 0.7652358 ,
       0.90254416, 0.47854617, 0.50260785, 0.03957477, 0.55318421])

In [74]:
np.random.binomial(n = 1, p = 0.5, size = 100)

array([1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1])

In [117]:
a = np.array([123435,3,3,33,4,3,3,3,])

In [119]:
a.mean()

15435.875

# Пример с прогнозами

In [28]:
import pandas as pd

In [29]:
flats_data = pd.read_csv('data_flat.csv')

In [30]:
flats_data

     transit  rooms  dist_metro  dist_center  area  floor  price
0          6      4          10          7.6   101      9  21.84
1          9      2           4          2.1    56     15  16.84
2          3      1          19          9.5    31      3   5.21
3          7      3           8          5.4    77     12  17.74
4          5      2          14          8.3    49      7  11.37
..       ...    ...         ...          ...   ...    ...    ...
96         7      3           7          4.7    80     13  18.76
97         4      2          19         10.0    45      5   8.42
98         9      3           3          1.9    68     12  19.67
99         6      3          10          5.5    77      6  16.23
100        3      2          22         11.4    49      8   8.97

[101 rows x 7 columns]

In [31]:
flats_data['w0'] = 1

In [32]:
flats_data

     transit  rooms  dist_metro  dist_center  area  floor  price  w0
0          6      4          10          7.6   101      9  21.84   1
1          9      2           4          2.1    56     15  16.84   1
2          3      1          19          9.5    31      3   5.21   1
3          7      3           8          5.4    77     12  17.74   1
4          5      2          14          8.3    49      7  11.37   1
..       ...    ...         ...          ...   ...    ...    ...  ..
96         7      3           7          4.7    80     13  18.76   1
97         4      2          19         10.0    45      5   8.42   1
98         9      3           3          1.9    68     12  19.67   1
99         6      3          10          5.5    77      6  16.23   1
100        3      2          22         11.4    49      8   8.97   1

[101 rows x 8 columns]

In [22]:
flats_data.columns

Index(['transit', 'rooms', 'dist_metro', 'dist_center', 'area', 'floor',
       'price'],
      dtype='object')

In [33]:
X = flats_data[['w0', 'transit', 'rooms', 'dist_metro', 'dist_center', 'area', 'floor']].to_numpy()

In [75]:
y = flats_data['price'].to_numpy()

In [111]:
ws = np.array([1,1,1,-1,-1, 1, 1])

In [105]:
abs(y - abs(X@ws)).mean()

5.6095787874959315

In [110]:
np.random.rand(2,7)*ws

array([[ 0.08046927,  0.11879789,  0.59706707, -0.02472519, -0.0321266 ,
         0.07228251,  0.38364555],
       [ 0.01487497,  0.01279102,  0.78794826, -0.00185869, -0.46014581,
         0.01567389,  0.20815151]])

In [112]:
from sklearn.linear_model import LinearRegression

In [113]:
my_model = LinearRegression()

In [114]:
my_model.fit(X, y)

LinearRegression()

In [115]:
abs(y - abs(my_model.predict(X))).mean()

0.4328704147011579

In [116]:
my_model.coef_

array([ 0.        ,  0.73390175,  0.14468805, -0.06729396, -0.20901942,
        0.15881322,  0.0893311 ])

Таким же образом можно было посмотреть на минимальное и максимальное значение (можете потренироваться самостоятельно).

### Создание массивов

#### Как создать массив?

**Способ 1**

С первым способом мы уже отчасти познакомились: можно получить массив из готового списка, воспользовавшись функцией `array()`:

In [75]:
np.array([10.5, 45, 2.4])

array([10.5, 45. ,  2.4])

**Способ 2**

Можно создать массив на основе промежутка, созданного с помощью `arange()` – функции `numpy`, похожей на стандартный `range()`, только более гибкую. Посмотрим, как работает эта функция.

In [76]:
np.arange(2, 9) # по умолчанию шаг равен 1, как обычный range()

array([2, 3, 4, 5, 6, 7, 8])

По умолчанию эта функция создает массив, элементы которого начинаются со значения 2 и заканчиваются на значении 8 (правый конец промежутка не включается), следуя друг за другом с шагом 1. Но этот шаг можно менять:

In [77]:
np.arange(2, 9, 3) # с шагом 3

array([2, 5, 8])

И даже делать дробным!

In [78]:
np.arange(2, 9, 0.5).tolist()

[2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0, 5.5, 6.0, 6.5, 7.0, 7.5, 8.0, 8.5]

Или создать массив из диапазона значений [start, stop] с заданием количества точек.

In [79]:
m = np.linspace(0, 6, 8)
m

array([0.        , 0.85714286, 1.71428571, 2.57142857, 3.42857143,
       4.28571429, 5.14285714, 6.        ])

**Способ 3**

Еще массив можно создать совсем с нуля. Единственное, что нужно четко представлять – это его размерность, его форму, то есть опять же, число строк и столбцов. Библиотека `numpy` позволяет создать массивы, состоящие из нулей или единиц, а также  «пустые» массивы (на практике используются редко). Удобство заключается в том, что сначала можно создать массив, инициализировать его (например, заполнить нулями), а затем заменить нули на другие значения в соответствии с требуемыми условиями.

Так выглядит массив из нулей:

In [80]:
Z = np.zeros((3, 3, 3)) # размеры в виде кортежа - не теряйте еще одни круглые скобки
Z

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [96]:
# создание вектора из нулей
v = np.zeros(4)
print(v)

[0. 0. 0. 0.]

А так – массив из единиц:

In [69]:
np.random.rand??

In [ ]:
np.random.

In [97]:
O = np.random.randn(4, 2)
O

array([[-1.46971105,  2.01091019],
       [ 2.10379581, -1.30682982],
       [ 0.42594891,  0.23581519],
       [ 0.06051801,  0.01583094]])

А так выглядит единичная матрица – таблица из 0 и 1, в которой число строк и столбцов одинаково, и где на главной диагонали стоят 1:

In [72]:
E = np.eye(5)
E

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### Создайте матрицу 5x5 со значениями строк в диапазоне от 0 до 4

In [78]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [77]:
m = np.zeros((5, 5))
print(m)
m += np.arange(5)
print(m)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]

**Способ 4**

Создание массива случайных чисел.

В `numpy` есть аналог модуля `random` - `numpy.random`. Используя типизацию из C, он как и свой аналог генерирует случайные данные.

In [98]:
np.random.rand(1, 1)

array([[0.15601864]])

In [102]:
# массив чисел из равномерного (uniform) распределения в диапазоне [0, 1)
# np.random.rand(d0, d1, d3, ...) d0, d1,... - pазмеры возвращаемого массива
np.random.seed(42)
print(np.random.rand(2, 2))
print(np.random.rand(2, 2).shape)

[[0.37454012 0.95071431]
 [0.73199394 0.59865848]]
(2, 2)

In [103]:
# массив чисел из стандартного нормального (norm) распределения
np.random.randn(2, 3, 2) 
# print(np.random.randn(2, 3, 2).shape)

array([[[ 1.57921282,  0.76743473],
        [-0.46947439,  0.54256004],
        [-0.46341769, -0.46572975]],

       [[ 0.24196227, -1.91328024],
        [-1.72491783, -0.56228753],
        [-1.01283112,  0.31424733]]])

In [99]:
a = np.array([0,0,0,0,0,0,0,0,0,0,1,1,1,1,1])

In [104]:
(a == 1).sum()

5

In [108]:
x = (np.random.choice(a=a, 
                 size=(5, 1000000), 
                 replace=True).sum(axis = 0)>=4).mean()

x

0.045395

In [107]:
i = 0
for _ in range(100000):
    if np.random.choice(a=a, size=5, replace=True).sum()>=4:
        i+=1
print(i/100000)

0.04515

In [40]:
# массив из случайно выбранных чисел
# size - размер возвращаемого массива, reaplce=False без замещения
np.random.choice(a=a, size=5, replace=False)

array([ 0, 17, 15,  1,  8])

In [110]:
np.random.choice(a=np.arange(20), size=(2, 3), replace=False)

array([[12, 13, 18],
       [ 4,  0, 15]])

## Почему нужно использовать векторизованные вычисления?

Несмотря на то, что для создания единичной матрицы есть специальный метод, давайте посмотрим, как бы мы создавали её «вручную». Для этого нам потребовались бы вложенные циклы:

In [112]:
%%time
I = np.zeros((100, 100))

for i in range(0, I.shape[0]):
    for j in range(0, I.shape[1]):
        if i == j:
            I[i][j] = 1
I

CPU times: user 1.29 ms, sys: 50 µs, total: 1.34 ms
Wall time: 1.32 ms

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [113]:
%%time
I = np.eye(100,100)
I

CPU times: user 75 µs, sys: 41 µs, total: 116 µs
Wall time: 142 µs

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [115]:
%%time
a = np.zeros(1000000, dtype=np.float64)
for i in range(1, 1000001):
    a[i - 1] = i ** 0.5
print(a)

[   1.            1.41421356    1.73205081 ...  999.999       999.9995
 1000.        ]
CPU times: user 334 ms, sys: 8.99 ms, total: 343 ms
Wall time: 471 ms

In [116]:
%%time
b = np.arange(1, 1000001, dtype=np.float64)
b = np.sqrt(b)
print(b)

[   1.            1.41421356    1.73205081 ...  999.999       999.9995
 1000.        ]
CPU times: user 4.8 ms, sys: 4.09 ms, total: 8.89 ms
Wall time: 14.9 ms

Данный пример заодно показывает одну важную особенность — массивы, как и списки, являются изменяемыми объектами в Python.

### Изменение размерности списков

Вспомним, что у нас есть массив оценок студентов `grades`:

In [96]:
grades

array([[3, 5, 5, 4, 3],
       [3, 3, 4, 3, 3],
       [5, 5, 5, 4, 5]])

Как поменять структуру массива так, чтобы, например, оценки были записаны группами по три оценки? Воспользоваться методом `.reshape()`, который позволяет поменять форму массива.

In [111]:
grades.reshape(5, 3)

array([[3, 5, 5],
       [4, 3, 3],
       [3, 4, 3],
       [3, 5, 5],
       [5, 4, 5]])

Теперь массив двумерный, и чтобы обратиться к элементу массива, нам нужно указывать две вещи: индекс списка и индекс элемента в этом списке. Метод `.reshape()` удобен, но при его использовании стоит помнить, что не любой массив можно превратить в массив другой формы – общее число элементов в массиве должно позволять получить новое число списков и элементов в них. Так, массив `grades`, в котором всего 15 элементов, нельзя превратить в массив вида `(2, 8)` (таблица $2 \times 8$), потому что для такой формы понадобится 16 элементов! И Python явно об этом сообщит:

In [81]:
grades.reshape(2, 8)

ValueError: cannot reshape array of size 15 into shape (2,8)

Если нам нужно просто поменять местами строки и столбцы в таблице, то есть списки в массиве, можно воспользоваться транспонированием, которое осуществляется в `NumPy` с помощью метода `.transpose()`:

In [82]:
grades.T

array([[3, 3, 5],
       [5, 3, 5],
       [5, 4, 5],
       [4, 3, 4],
       [3, 3, 5]])

In [83]:
grades.transpose()

array([[3, 3, 5],
       [5, 3, 5],
       [5, 4, 5],
       [4, 3, 4],
       [3, 3, 5]])

Кроме того, в противоположность `.reshape()`, который часто используется для разбиения одномерного массива на многомерный из нескольких маленьких списков, в `NumPy` существует «обратный» метод `.ravel()`, который позволяет любой многомерный массив превратить в одномерный, состоящий из одного списка, другими словами, сделать массив «плоским»:

In [85]:
grades.ravel()

array([3, 5, 5, 4, 3, 3, 3, 4, 3, 3, 5, 5, 5, 4, 5])

In [84]:
grades.flatten()

array([3, 5, 5, 4, 3, 3, 3, 4, 3, 3, 5, 5, 5, 4, 5])

*Примечание:* в `NumPy` есть ещё другой метод для создания «плоских» массивов – `flatten()`.

### Проверка условий на массивах

Давайте посмотрим, каким образом можно проверять условия на массивах и отбирать элементы по условию. Создадим массив со значениями возраста:

In [86]:
ages = np.array([[15, 23, 32, 45, 52], 
               [68, 34, 55, 78, 20], 
               [25, 67, 33, 45, 14]])

Давайте попробуем узнать, какие значения массива соответствуют людям трудоспособного возраста: от 16 лет и старше:

In [87]:
ages >= 16  # больше или равно

array([[False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False]])

Все элементы, кроме первого в первом списке и кроме последнего в последнем списке: на всех позициях, кроме указанных, стоят значения `True`, что означает, что условие выполняется. То, что мы получили сейчас – это булев массив, массив, состоящий из булевых (логических) значений, значений `True` и `False`. 

Теперь попробуем сформулировать более сложное условие: проверим, какие элементы соответствуют людям старше 18, но младше 60 лет:

In [88]:
(ages > 18) & (ages < 60) # & - одновременное условие

array([[False,  True,  True,  True,  True],
       [False,  True,  True, False,  True],
       [ True, False,  True,  True, False]])

Как посчитать, сколько элементов массива удовлетворяют некоторым условиям?

Суммируем значения по всему массиву: Python понимает, что значение `True` – это 1, а `False` – это 0, поэтому нет необходимости превращать все значения в числовые, мы можем просто сложить все «единички»:

In [89]:
((ages > 18) & (ages < 60)).sum()

10

А теперь проверим, какие значения соответствуют людям либо младше 18, либо старше 60:

In [127]:
(ages < 18) | (ages > 60)  # | - или - хотя бы одно условие верно

array([[ True, False, False, False, False],
       [ True, False, False,  True, False],
       [False,  True, False, False,  True]])

А как увидеть сами значения, которые удовлетворяют определенным условиям? Заключить условие в квадратные скобочки:

In [128]:
ages 
# >= 16

array([[15, 23, 32, 45, 52],
       [68, 34, 55, 78, 20],
       [25, 67, 33, 45, 14]])

In [90]:
ages[ages >= 16]

array([23, 32, 45, 52, 68, 34, 55, 78, 20, 25, 67, 33, 45])

In [91]:
ages[~((ages >= 16) & (ages < 60))]

array([15, 68, 78, 67, 14])

Внимание: не забудьте круглые скобки для каждого условия, иначе Python поймёт всё неправильно и вернёт ошибку:

In [122]:
ages[ages >= 16 & ages < 60]

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

### Запись списков в файл и чтение файлов со списками

Чтобы было проще работать, сначала обсудим запись списков, тем самым сохранив списки себе на компьютер, а потом будем загружать их в Python. Это удобно для хранения больших списков с данными + например, для сохранения результатов разных моделей.

Запишем массив `ages` в файл формата `.npy`: сначала укажем название файла, а затем – сам массив, который сохраняем.

In [123]:
import os
os.getcwd()

'/Users/i.pile/Documents/GitHub/DPO_Python_2023/lect13_Numpy'

In [124]:
np.save("ages.npy", ages)

Теперь этот файл можно увидеть во вкладке *Home* в Jupyter Notebook, в рабочей папке. Попробуем выполнить обратную операцию: считаем массив из numpy-файла:

In [125]:
np.load("ages.npy")

array([[15, 23, 32, 45, 52],
       [68, 34, 55, 78, 20],
       [25, 67, 33, 45, 14]])

Выгружать списки можно в разные форматы. Например, можно просто сохранить массив в текстовый файл с расширением `.txt`:

In [126]:
np.savetxt("ages.txt", ages)

И аналогичным образом считать:

In [127]:
np.loadtxt("ages.txt")

array([[15., 23., 32., 45., 52.],
       [68., 34., 55., 78., 20.],
       [25., 67., 33., 45., 14.]])

Если нет необходимости работать с файлами, можем просто превратить массив в другой объект Python. Например, в обычный список:

In [136]:
ages.tolist()

[[15, 23, 32, 45, 52], [68, 34, 55, 78, 20], [25, 67, 33, 45, 14]]

Или строку:

In [137]:
np.array2string(ages)

'[[15 23 32 45 52]\n [68 34 55 78 20]\n [25 67 33 45 14]]'

13.711309200802088

In [100]:
a = np.array([2,3,5,8,3,6,4,5])
b = 2*np.array([2,3,5,8,3,6,4,5])

In [103]:
b

array([ 4,  6, 10, 16,  6, 12,  8, 10])

In [101]:
a_l = np.sqrt((a**2).sum())
b_l = np.sqrt((b**2).sum())

In [102]:
(a@b)/(a_l*b_l)

1.0

# Операции с векторами и матрицами в нампай

#### Скалярное произведение векторов

In [129]:
a = np.array([3, 1, 5, 2])
b = np.array([2, 5, 2, 4])
# <a, b> = 3*1 + 1*5 + 5*2 + 2*4
print(a @ b)    # python 3 style
print(a.dot(b)) 
print(np.dot(a, b))

29
29
29

In [130]:
a = np.array([3, 1, 5, 2])
b = np.array([2, 5, 2, 4, 4])
print(a @ b)    # python 3 style

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 5 is different from 4)

#### Умножение матриц
  
Операция умножения определена для двух матриц, таких что число столбцов первой равно числу строк второй. 

Пусть матрицы $A$ и $B$ таковы, что $A \in \mathbb{R}^{n \times k}$ и $B \in \mathbb{R}^{k \times m}$.    
__Произведением__ матриц $A$ и $B$ называется матрица $C$, такая что 
$$c_{ij} = \sum_{r=1}^{k} a_{ir}b_{rj}$$, 
где  $c_{ij}$ — элемент матрицы $C$, стоящий на пересечении строки с номером $i$ и столбца с номером $j$.

In [131]:
a = np.array([[1, 2], [2, 0]])
b = np.array([[2,5], [1, 3]])
# print(a)
# print(b)
print(a @ b)    # python 3 style
print(a.dot(b)) 
print(np.dot(a, b))

[[ 4 11]
 [ 4 10]]
[[ 4 11]
 [ 4 10]]
[[ 4 11]
 [ 4 10]]

In [142]:
a = np.array([[1, 2], [2, 0]])
b = np.array([1, 2])
print(a @ b)

[5 2]

**!!!Не путайте поокординатное умножение с матричным!!!**

In [132]:
print(a * b)

[[ 2 10]
 [ 2  0]]

#### Умножение матриц и векторов

In [143]:
m = np.array([[1, 2], [0, 1], [2, 4]])
print(m)
v = np.array([2, 5])
print("v = ",v)
m @ v

[[1 2]
 [0 1]
 [2 4]]
v =  [2 5]

array([12,  5, 24])

## Полезные фукнции и методы для работы с массивами

In [144]:
a = np.random.choice(a=np.linspace(1, 50, 50), size=10, replace=True)
print(a)

[15.  4. 39. 34. 18. 49. 28.  8. 11. 16.]

**1. Замена элементов по индексу**

In [145]:
np.put(a, ind=[0, 2], v=[-44, -55])
a

array([-44.,   4., -55.,  34.,  18.,  49.,  28.,   8.,  11.,  16.])

**2. Выделение массива по условию**

In [147]:
# замена элементов массива по условию: a if a < 0 else 0
np.where(a < 0, a, 0)

array([-44.,   0., -55.,   0.,   0.,   0.,   0.,   0.,   0.,   0.])

In [148]:
# выбор элементов по условию
a[np.where(a < 0)]

array([-44., -55.])

**3. Сортировка**

In [149]:
# сортировка
np.sort(a)

array([-55., -44.,   4.,   8.,  11.,  16.,  18.,  28.,  34.,  49.])

In [150]:
# индексы сортированного списка
np.argsort(a)

array([2, 0, 1, 7, 8, 9, 4, 6, 3, 5])

**4. Any и All для сложных логических условий**

`Any` возвращает True, если хотя бы один элемент `True`   
`All` возвращает True, если все эедементы `True`

In [151]:
any([True, True, False, True, False, False, False])

True

In [152]:
all([True, True, False, True, False, False, False])

False

In [153]:
# сравнение векторов
np.array([1, 1, 0, 0]) == np.array([1, 1, 0, 2])

array([ True,  True,  True, False])

In [111]:
all(np.array([1, 1, 0, 0]) == np.array([1, 1, 0, 2]))

False

In [154]:
any(np.array([1, 1, 0, 0]) == np.array([1, 1, 0, 2]))

True